# CrateKeys configuration (created by SavionLegendZzz)
---
Crate: 19
# CrateKeys block (please use IDs)

CrateKey-Item: 341
# CrateKey item

failed: "You Need A Crate Key Too Open The Crate!"
# CrateKey failed message

completed: "Items Added Into Your Inventroy!"
ID-1: 0
ID-2: 255
# The items go from 0 to 255 by ID.

number-of-items: 1
# How many of a certain item you would get.
...
